// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	schedulingv1 "github.com/kaschnit/kaschnit-scheduler/apis/scheduling/v1"
	scheme "github.com/kaschnit/kaschnit-scheduler/client/clientset/scheduling/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// QueuesGetter has a method to return a QueueInterface.
// A group's client should implement this interface.
type QueuesGetter interface {
	Queues() QueueInterface
}

// QueueInterface has methods to work with Queue resources.
type QueueInterface interface {
	Create(ctx context.Context, queue *schedulingv1.Queue, opts metav1.CreateOptions) (*schedulingv1.Queue, error)
	Update(ctx context.Context, queue *schedulingv1.Queue, opts metav1.UpdateOptions) (*schedulingv1.Queue, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, queue *schedulingv1.Queue, opts metav1.UpdateOptions) (*schedulingv1.Queue, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*schedulingv1.Queue, error)
	List(ctx context.Context, opts metav1.ListOptions) (*schedulingv1.QueueList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *schedulingv1.Queue, err error)
	QueueExpansion
}

// queues implements QueueInterface
type queues struct {
	*gentype.ClientWithList[*schedulingv1.Queue, *schedulingv1.QueueList]
}

// newQueues returns a Queues
func newQueues(c *SchedulingV1Client) *queues {
	return &queues{
		gentype.NewClientWithList[*schedulingv1.Queue, *schedulingv1.QueueList](
			"queues",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *schedulingv1.Queue { return &schedulingv1.Queue{} },
			func() *schedulingv1.QueueList { return &schedulingv1.QueueList{} },
		),
	}
}
