// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	schedulingv1 "github.com/kaschnit/kaschnit-scheduler/apis/scheduling/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// QueueLister helps list Queues.
// All objects returned here must be treated as read-only.
type QueueLister interface {
	// List lists all Queues in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*schedulingv1.Queue, err error)
	// Get retrieves the Queue from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*schedulingv1.Queue, error)
	QueueListerExpansion
}

// queueLister implements the QueueLister interface.
type queueLister struct {
	listers.ResourceIndexer[*schedulingv1.Queue]
}

// NewQueueLister returns a new QueueLister.
func NewQueueLister(indexer cache.Indexer) QueueLister {
	return &queueLister{listers.New[*schedulingv1.Queue](indexer, schedulingv1.Resource("queue"))}
}
