// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kaschnit/kaschnit-scheduler/apis/scheduling/v1"
	schedulingv1 "github.com/kaschnit/kaschnit-scheduler/client/clientset/scheduling/typed/scheduling/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeQueues implements QueueInterface
type fakeQueues struct {
	*gentype.FakeClientWithList[*v1.Queue, *v1.QueueList]
	Fake *FakeSchedulingV1
}

func newFakeQueues(fake *FakeSchedulingV1) schedulingv1.QueueInterface {
	return &fakeQueues{
		gentype.NewFakeClientWithList[*v1.Queue, *v1.QueueList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("queues"),
			v1.SchemeGroupVersion.WithKind("Queue"),
			func() *v1.Queue { return &v1.Queue{} },
			func() *v1.QueueList { return &v1.QueueList{} },
			func(dst, src *v1.QueueList) { dst.ListMeta = src.ListMeta },
			func(list *v1.QueueList) []*v1.Queue { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.QueueList, items []*v1.Queue) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
