// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kaschnit/kaschnit-scheduler/client/clientset/scheduling/typed/scheduling/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSchedulingV1 struct {
	*testing.Fake
}

func (c *FakeSchedulingV1) Queues() v1.QueueInterface {
	return newFakeQueues(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSchedulingV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
