// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/kaschnit/kaschnit-scheduler/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Queues returns a QueueInformer.
	Queues() QueueInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Queues returns a QueueInformer.
func (v *version) Queues() QueueInformer {
	return &queueInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
