//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreemptionConfig) DeepCopyInto(out *PreemptionConfig) {
	*out = *in
	if in.MaxCandidateNodes != nil {
		in, out := &in.MaxCandidateNodes, &out.MaxCandidateNodes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreemptionConfig.
func (in *PreemptionConfig) DeepCopy() *PreemptionConfig {
	if in == nil {
		return nil
	}
	out := new(PreemptionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaAwarePreemptionArgs) DeepCopyInto(out *QuotaAwarePreemptionArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Preemption.DeepCopyInto(&out.Preemption)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaAwarePreemptionArgs.
func (in *QuotaAwarePreemptionArgs) DeepCopy() *QuotaAwarePreemptionArgs {
	if in == nil {
		return nil
	}
	out := new(QuotaAwarePreemptionArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuotaAwarePreemptionArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
